# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.5.0
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/dps-visualiser

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # install project!
      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: yarn test

      # dist!
      - run: yarn dist

      # store dist
      - store_artifacts:
          path: artifacts/dist
          destination: dist

      # store coverage
      - store_artifacts:
          path: artifacts/coverage
          destination: coverage

      # store test results
      # we add /Jest/ because CircleCI infers the name of the test runner from the folder structure
      - store_artifacts:
          path: artifacts/test-results/Jest
          destination: test-results

     # store test results
     # we add /Jest/ because CircleCI infers the name of the test runner from the folder structure
      - store_test_results:
          path: artifacts/test-results